name: 'Deploy Qt Creator Extension'
description: 'Deploys a Qt Creator Extension to the Qt Creator Extension Store'
author: 'The Qt Company'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'green'

# Define your inputs here.
inputs:
  spec:
    description: 'Path to the plugin spec'
    required: true
  api:
    description: 'Path to the Extension store api'
    required: true
  token:
    description: 'Your API Token for the Extension Store'
    required: true
  download-url-win-x64:
    description: 'The url to download the extension from (for Windows x64)'
    required: false
  download-url-win-arm64:
    description: 'The url to download the extension from (for Windows ARM64)'
    required: false
  download-url-macos-x64:
    description: 'The url to download the extension from (for macOS x86)'
    required: false
  download-url-macos-arm64:
    description: 'The url to download the extension from (for macOS ARM64)'
    required: false
  download-url-linux-x64:
    description: 'The url to download the extension from (for Linux x64)'
    required: false
  download-url-linux-arm64:
    description: 'The url to download the extension from (for Linux ARM64)'
    required: false
  publish:
    description: 'Whether to immediately set status to "published"'
    required: false
    default: 'false'

# Define your outputs here.
#outputs:
#  time:
#    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
